use NORTHWND

-- VIET CAU LENH SQL LAY RA TEN CAC QUOC GIA KHAC NHAU TU BANG KHACH HANG
SELECT DISTINCT Country
FROM dbo.Customers

-- VIET CAU LENH SQL LAY RA TEN CAC MA SO BUU DIEN KHAC NHAU TU NHA CUNG CAP
SELECT DISTINCT PostalCode
FROM dbo.Suppliers 

-- VIET CAU LENH SQL LAY RA HO(LastName) KHAC NHAU VA DANH HIEU LICH SU(TitleOfCourtesy) CUA NHAN VIEN TU BANG NHAN VIEN
SELECT DISTINCT LastName, TitleOfCourtesy
FROM dbo.Employees

-- MA DON VI VAN CHUYEN (ShipVia) KHAC NHAU CUA BANG DON HANG
SELECT DISTINCT ShipVia
FROM dbo.Orders